name: diebold
dependencies:
- anaconda-client=1.4.0=py27_0
- appnope=0.1.0=py27_0
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- clyent=1.2.2=py27_0
- configparser=3.5.0b2=py27_1
- cycler=0.10.0=py27_0
- decorator=4.0.9=py27_0
- entrypoints=0.2=py27_1
- freetype=2.5.5=0
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- ipykernel=4.3.1=py27_0
- ipython=4.2.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_2
- jupyter_client=4.2.2=py27_0
- jupyter_console=4.1.1=py27_0
- jupyter_core=4.1.0=py27_0
- libpng=1.6.17=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np111py27_0
- mistune=0.7.2=py27_1
- mkl=11.3.1=0
- nbconvert=4.2.0=py27_0
- nbformat=4.0.1=py27_0
- notebook=4.2.0=py27_0
- numpy=1.11.0=py27_0
- openssl=1.0.2h=0
- pandas=0.18.1=np111py27_0
- path.py=8.2.1=py27_0
- patsy=0.4.1=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.5=py27_0
- pip=8.1.1=py27_1
- ptyprocess=0.5=py27_0
- pygments=2.1.3=py27_0
- pyparsing=2.1.1=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.5.2=py27_0
- pytz=2016.3=py27_0
- pyyaml=3.11=py27_1
- pyzmq=15.2.0=py27_0
- qt=4.8.7=1
- qtconsole=4.2.1=py27_0
- readline=6.2=2
- requests=2.9.1=py27_0
- scipy=0.17.0=np111py27_0
- seaborn=0.7.0=py27_0
- setuptools=20.7.0=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_1
- statsmodels=0.6.1=np111py27_0
- terminado=0.5=py27_1
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.2.1=py27_0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - plotly==1.9.10

